{% set name = "metadetect" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/metadetect/archive/{{ version }}.tar.gz
  sha256: 0a4d0ae786ab51c0d9a2a21059d9d9d9c6080100ba679296b9df4619c4e87550

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - galsim
    - fitsio >=1.0
    - pyyaml
    - numba
    - esutil
    - sep
    - meds
    - ngmix >=2.3.0
    - des-sxdes >=0.3.0  # needed for correct default detection config
    - setuptools <82 # needed for pkg_resources

test:
  requires:
    - python {{ python_min }}
  imports:
    - metadetect

about:
  home: https://github.com/esheldon/metadetect
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Library for meta-detection, combining detection and metacalibration

extra:
  recipe-maintainers:
    - beckermr
