{% set name = "metadetect" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/metadetect/archive/{{ version }}.tar.gz
  sha256: f434e44ff3dd8e17c379d4e48fc0bb0a7585b2f0d297e153724253d326ead1e9

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - galsim
    - fitsio >=1.0
    - pyyaml
    - numba
    - esutil
    - sep
    - meds
    - ngmix >=2.3.0
    - des-sxdes >=0.3.0  # needed for correct default detection config
    - setuptools  # needed for pkg_resources

test:
  requires:
    - python {{ python_min }}
  imports:
    - metadetect

about:
  home: https://github.com/esheldon/metadetect
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Library for meta-detection, combining detection and metacalibration

extra:
  recipe-maintainers:
    - beckermr
