{% set name = "metadetect" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/metadetect/archive/{{ version }}.tar.gz
  sha256: 6679afd3ef7ff978620bf9bcbcefdd5c557045385f8deda16837454657758da2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - galsim
    - fitsio >=1.0
    - pyyaml
    - numba
    - esutil
    - sep
    - meds
    - ngmix
    - des-sxdes

test:
  imports:
    - metadetect

about:
  home: https://github.com/esheldon/metadetect
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Library for meta-detection, combining detection and metacalibration

extra:
  recipe-maintainers:
    - beckermr
