{% set name = "metadetect" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/metadetect/archive/{{ version }}.tar.gz
  sha256: 3819570fdd07fd228d994915d5f8fca8970cf18a43d0fa12dae277b1ccc689b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - galsim
    - fitsio >=1.0
    - pyyaml
    - numba
    - esutil
    - sep
    - meds
    - ngmix >=2.1.0
    - des-sxdes >=0.3.0  # needed for correct default detection config
    - setuptools  # needed for pkg_resources

test:
  imports:
    - metadetect

about:
  home: https://github.com/esheldon/metadetect
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Library for meta-detection, combining detection and metacalibration

extra:
  recipe-maintainers:
    - beckermr
