{% set name = "metadetect" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/metadetect/archive/{{ version }}.tar.gz
  sha256: e2a4721db0e982bf47672b43e19586c6a2ccfd4af3faf8770e865bdce223e30e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - galsim
    - fitsio >=1.0
    - pyyaml
    - numba
    - esutil
    - sep
    - meds
    - ngmix >=2.0.3
    - des-sxdes

test:
  imports:
    - metadetect

about:
  home: https://github.com/esheldon/metadetect
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Library for meta-detection, combining detection and metacalibration

extra:
  recipe-maintainers:
    - beckermr
